[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Allister Isaiah Harvey"]

[workspace]
resolver = "2"
members = ["crates/*", "crates/*/examples/*"]


[workspace.dependencies]
derive_more = "1.0.0"
itertools = "0.13.0"
leptos = "0.6.14"
leptos-use = "0.13.0"
web-sys = "0.3.70"
